<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251104185044 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE csv (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code UUID NOT NULL, filename VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status INT NOT NULL, errors TEXT DEFAULT NULL, type INT NOT NULL, seller_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A452578DE820D9 ON csv (seller_id)');
        $this->addSql('CREATE TABLE seller (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code UUID NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FB1AD3FC77153098 ON seller (code)');
        $this->addSql('CREATE TABLE settlement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, settlement_id VARCHAR(255) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, deposit_date DATE NOT NULL, total_amount NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) NOT NULL, seller_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DD9F1B51C2B9C425 ON settlement (settlement_id)');
        $this->addSql('CREATE INDEX IDX_DD9F1B518DE820D9 ON settlement (seller_id)');
        $this->addSql('CREATE TABLE transaction_total (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, transaction_type VARCHAR(255) NOT NULL, amount_type VARCHAR(255) NOT NULL, amount_description VARCHAR(255) NOT NULL, total_amount NUMERIC(10, 2) NOT NULL, year INT NOT NULL, month INT NOT NULL, total_type VARCHAR(4) NOT NULL, settlement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_631C311EC2B9C425 ON transaction_total (settlement_id)');
        $this->addSql('CREATE TABLE units_sold (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sku VARCHAR(255) NOT NULL, quantity_purchased INT NOT NULL, year INT NOT NULL, month INT NOT NULL, total_amount NUMERIC(12, 2) NOT NULL, settlement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3EAB16C4C2B9C425 ON units_sold (settlement_id)');
        $this->addSql('ALTER TABLE csv ADD CONSTRAINT FK_8A452578DE820D9 FOREIGN KEY (seller_id) REFERENCES seller (id)');
        $this->addSql('ALTER TABLE settlement ADD CONSTRAINT FK_DD9F1B518DE820D9 FOREIGN KEY (seller_id) REFERENCES seller (id)');
        $this->addSql('ALTER TABLE transaction_total ADD CONSTRAINT FK_631C311EC2B9C425 FOREIGN KEY (settlement_id) REFERENCES settlement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE units_sold ADD CONSTRAINT FK_3EAB16C4C2B9C425 FOREIGN KEY (settlement_id) REFERENCES settlement (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE csv DROP CONSTRAINT FK_8A452578DE820D9');
        $this->addSql('ALTER TABLE settlement DROP CONSTRAINT FK_DD9F1B518DE820D9');
        $this->addSql('ALTER TABLE transaction_total DROP CONSTRAINT FK_631C311EC2B9C425');
        $this->addSql('ALTER TABLE units_sold DROP CONSTRAINT FK_3EAB16C4C2B9C425');
        $this->addSql('DROP TABLE csv');
        $this->addSql('DROP TABLE seller');
        $this->addSql('DROP TABLE settlement');
        $this->addSql('DROP TABLE transaction_total');
        $this->addSql('DROP TABLE units_sold');
    }
}
